### ISSUE TITLE
Body part column of model-decoder.png does not include 'H' for hand

### ISSUE THREAD

**Issue by lucaswerkmeister** [wearebeautiful/wearebeautiful-web#2]
Just a minor thing I noticed while trying to process the model codes: the `web/static/img/model-decoder.png`, shown on https://wearebeautiful.info/docs/model-codes, is missing the `H` body part letter (“hand”). (Everything else seems to be complete, at least as far as the current `*-manifest.json` files in the models repository go.)

**Comment by mayhem** [comment]
Thanks for this bug report -- fixed and deployed. 

I'm curious -- how did you find this site? We've been unable to raise people's interest in looking at the site, so I am curious as to how you found it.

Thanks!

**Comment by lucaswerkmeister** [comment]
A friend saw your initial announcement on Twitter but didn’t look closer into it until a few weeks later ([tweet](https://twitter.com/xdr5/status/1315023871658078213)); since then, I’ve started importing the models into Wikimedia Commons ([code](https://github.com/lucaswerkmeister/wearebeautiful-commons/), [category with files](https://commons.wikimedia.org/wiki/Category:We_Are_Beautiful)), since I think there’s a clear educational benefit and we didn’t have anything similar yet :)

**Comment by mayhem** [comment]
THANK YOU for doing this -- I agree and this should help the visibility of the project as well. :)
